// Lightweight printable HTML generator — opens a new window and triggers print.
// No native binaries / external deps, works in Worker SSR + browser.
import { inr } from "./format";

export interface InvoiceLine { product: string; qty: number; unit: number; total: number }
export interface InvoiceData {
  invoiceNo: string;
  date: string;
  customer?: string | null;
  customerAddress?: string | null;
  lines: InvoiceLine[];
  subtotal: number;
  paid?: number;
  paymentType?: string;
  notes?: string | null;
}

const css = `
  *{box-sizing:border-box;font-family:'Inter',-apple-system,sans-serif;margin:0;padding:0;color:#111}
  body{padding:32px;max-width:760px;margin:0 auto}
  .hdr{display:flex;justify-content:space-between;align-items:flex-start;padding-bottom:16px;border-bottom:2px solid #111}
  .brand h1{font-size:24px;font-weight:700;letter-spacing:-.02em}
  .brand p{font-size:12px;color:#666;margin-top:2px}
  .meta{text-align:right;font-size:13px;color:#444}
  .meta strong{color:#111}
  .parties{display:grid;grid-template-columns:1fr 1fr;gap:20px;padding:20px 0;font-size:13px}
  .parties h3{font-size:11px;text-transform:uppercase;color:#888;letter-spacing:.05em;margin-bottom:4px}
  table{width:100%;border-collapse:collapse;margin-top:8px;font-size:13px}
  th{text-align:left;padding:10px 8px;background:#f5f5f5;font-weight:600;font-size:11px;text-transform:uppercase;letter-spacing:.04em;color:#555}
  th.r,td.r{text-align:right}
  td{padding:10px 8px;border-bottom:1px solid #eee}
  .totals{margin-top:16px;margin-left:auto;width:280px;font-size:14px}
  .totals .row{display:flex;justify-content:space-between;padding:6px 0}
  .totals .grand{border-top:2px solid #111;margin-top:8px;padding-top:10px;font-weight:700;font-size:16px}
  .ftr{margin-top:40px;padding-top:16px;border-top:1px solid #eee;font-size:11px;color:#888;text-align:center}
  .badge{display:inline-block;padding:2px 8px;border-radius:4px;font-size:11px;text-transform:uppercase;background:#111;color:#fff}
  @media print{body{padding:16px} .noprint{display:none}}
`;

export function renderInvoiceHTML(d: InvoiceData): string {
  return `<!doctype html><html><head><meta charset="utf-8"><title>Invoice ${d.invoiceNo}</title>
<style>${css}</style></head><body>
  <div class="hdr">
    <div class="brand"><h1>JR Bakery</h1><p>Tax Invoice</p></div>
    <div class="meta"><div><strong>Invoice #</strong> ${escapeHtml(d.invoiceNo)}</div><div><strong>Date</strong> ${escapeHtml(d.date)}</div></div>
  </div>
  <div class="parties">
    <div><h3>Billed To</h3><div><strong>${escapeHtml(d.customer || "Walk-in customer")}</strong></div>${d.customerAddress ? `<div style="color:#666;margin-top:2px">${escapeHtml(d.customerAddress)}</div>` : ""}</div>
    <div style="text-align:right"><h3>Payment</h3><span class="badge">${escapeHtml(d.paymentType || "cash")}</span></div>
  </div>
  <table>
    <thead><tr><th>Item</th><th class="r">Qty</th><th class="r">Unit</th><th class="r">Total</th></tr></thead>
    <tbody>${d.lines.map(l => `<tr><td>${escapeHtml(l.product)}</td><td class="r">${l.qty}</td><td class="r">${inr(l.unit)}</td><td class="r">${inr(l.total)}</td></tr>`).join("")}</tbody>
  </table>
  <div class="totals">
    <div class="row"><span>Subtotal</span><span>${inr(d.subtotal)}</span></div>
    ${d.paid ? `<div class="row"><span>Paid</span><span>${inr(d.paid)}</span></div><div class="row"><span>Due</span><span>${inr(d.subtotal - d.paid)}</span></div>` : ""}
    <div class="row grand"><span>Total</span><span>${inr(d.subtotal)}</span></div>
  </div>
  ${d.notes ? `<div style="margin-top:24px;font-size:12px;color:#666"><strong>Notes:</strong> ${escapeHtml(d.notes)}</div>` : ""}
  <div class="ftr">Thank you for your business. — generated by JR Bakery ERP</div>
  <script>window.onload=()=>setTimeout(()=>window.print(),250)</script>
</body></html>`;
}

export function openInvoicePDF(d: InvoiceData) {
  const w = window.open("", "_blank");
  if (!w) return;
  w.document.write(renderInvoiceHTML(d));
  w.document.close();
}

function escapeHtml(s: string) {
  return String(s).replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]!));
}
